site_name: MSE - CPSC-543 - Software Maintenance
site_url: https://conglesolutionx.github.io/MSE_CPSC-543-Software_Maintenance/

nav:
  - Introduction: 'index.md'
  - Syllabus: 'Syllabus.md'
  - Software Maintenance:
    - Chapter 1:
      - Chapter Overview: 'Software_Maintenance/Chapter_1/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_1/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_1/Discussing_Subjects.md'
    - Chapter 2:
      - Chapter Overview: 'Software_Maintenance/Chapter_2/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_2/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_2/Discussing_Subjects.md'
    - Chapter 3:
      - Chapter Overview: 'Software_Maintenance/Chapter_3/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_3/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_3/Discussing_Subjects.md'
    - Chapter 4:
      - Chapter Overview: 'Software_Maintenance/Chapter_4/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_4/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_4/Discussing_Subjects.md'
    - Chapter 5:
      - Chapter Overview: 'Software_Maintenance/Chapter_5/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_5/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_5/Discussing_Subjects.md'


theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/library-shelves

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: orange
      accent: amber

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep orange
      accent: green

# Plugins
plugins:
  - search
  - mermaid2

markdown_extensions:
  smarty: {}
  toc:
    permalink: true
  sane_lists: {}

  # pymdownx.superfences:
  #     # make exceptions to highlighting of code:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format


# # Add toggle for English and Vietnamese language
#   extra:
#   alternate:
#     - name: English
#       link: /en/
#       lang: en
#     - name: Vietnamese
#       link: /vi/
#       lang: vi
