site_name: MSE - CPSC-543 - Software Maintenance
# site_url: "CHANGE_ME_LATER"

nav:
  - Introduction: 'index.md'
  - Syllabus: 'Syllabus.md'
  - Textbook: 'Chapter_1/Chapter_1.md/'

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/library-shelves

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: orange
      accent: amber

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep orange
      accent: green

# Plugins
plugins:
  - search

markdown_extensions:
  smarty: {}
  toc:
    permalink: true
  sane_lists: {}
  pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


# # Add toggle for English and Vietnamese language
#   extra:
#   alternate:
#     - name: English
#       link: /en/
#       lang: en
#     - name: Vietnamese
#       link: /vi/
#       lang: vi
