site_name: MSE - CPSC-543 - Software Maintenance
site_url: https://conglesolutionx.github.io/MSE_CPSC-543-Software_Maintenance/

nav:
  - Introduction: 'index.md'
  - Syllabus: 'Syllabus.md'
  - Software Maintenance:
    - Chapter 1:
      - Chapter Overview: 'Software_Maintenance/Chapter_1/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_1/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_1/Discussion_Subjects.md'
    - Chapter 2:
      - Chapter Overview: 'Software_Maintenance/Chapter_2/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_2/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_2/Discussion_Subjects.md'
    - Chapter 3:
      - Chapter Overview: 'Software_Maintenance/Chapter_3/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_3/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_3/Discussion_Subjects.md'
    - Chapter 4:
      - Chapter Overview: 'Software_Maintenance/Chapter_4/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_4/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_4/Discussion_Subjects.md'
    - Chapter 5:
      - Chapter Overview: 'Software_Maintenance/Chapter_5/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_5/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_5/Discussion_Subjects.md'
    - Chapter 6:
      - Chapter Overview: 'Software_Maintenance/Chapter_6/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_6/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_6/Discussion_Subjects.md'
    - Chapter 7:
      - Chapter Overview: 'Software_Maintenance/Chapter_7/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_7/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_7/Discussion_Subjects.md'
    - Chapter 8:
      - Chapter Overview: 'Software_Maintenance/Chapter_8/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_8/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_8/Discussion_Subjects.md'
    - Chapter 9:
      - Chapter Overview: 'Software_Maintenance/Chapter_9/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_9/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_9/Discussion_Subjects.md'
    - Chapter 10:
      - Chapter Overview: 'Software_Maintenance/Chapter_10/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_10/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_10/Discussion_Subjects.md'
    - Chapter 11:
      - Chapter Overview: 'Software_Maintenance/Chapter_11/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_11/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_11/Discussion_Subjects.md'
    - Chapter 12:
      - Chapter Overview: 'Software_Maintenance/Chapter_12/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_12/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_12/Discussion_Subjects.md'
    - Chapter 13:
      - Chapter Overview: 'Software_Maintenance/Chapter_13/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_13/Chapter_Summary.md'
      - Discussing Subjects:
        - Subject 1: 'Software_Maintenance/Chapter_13/Discussion_Subject_1.md'
        - Subject 2: 'Software_Maintenance/Chapter_13/Discussion_Subject_2.md'
    - Chapter 14:
      - Chapter Overview: 'Software_Maintenance/Chapter_14/Chapter_Overview.md'
      - Chapter Summary: 'Software_Maintenance/Chapter_14/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Chapter_14/Discussion_Subjects.md'
    - PART V:
      - Chapter Overview: 'Software_Maintenance/Part_V/Part_V-Looking_to_the_future.md'
      - Chapter Summary: 'Software_Maintenance/Part_V/Chapter_Summary.md'
      - Discussing Subjects: 'Software_Maintenance/Part_V/Discussion_Subjects.md'


theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/library-shelves

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: orange
      accent: amber

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep orange
      accent: green

# Plugins
plugins:
  - search
  - mermaid2

markdown_extensions:
  smarty: {}
  toc:
    permalink: true
  sane_lists: {}

  # pymdownx.superfences:
  #     # make exceptions to highlighting of code:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format


# # Add toggle for English and Vietnamese language
#   extra:
#   alternate:
#     - name: English
#       link: /en/
#       lang: en
#     - name: Vietnamese
#       link: /vi/
#       lang: vi
