site_name: MSE - CPSC-543 - Software Maintenance
# site_url: "CHANGE_ME_LATER"

nav:
  - Introduction: 'index.md'
  - Syllabus: 'Syllabus.md'
  - Textbook: 'Chapter_1/Chapter_1.md/'

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/library-shelves

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: orange
      accent: amber

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep orange
      accent: green

# Plugins
plugins:
  - search
  - glightbox
  - mermaid2:
        version: '9.4.3' # only works with version < 10
        arguments:
          theme: 'dark'
          themeVariables:
            primaryColor: '#BB2528'
            primaryTextColor: '#fff'
            primaryBorderColor: '#7C0000'
            lineColor: '#F8B229'
            secondaryColor: '#006100'
            tertiaryColor: '#fff'

markdown_extensions:
  smarty: {}
  toc:
    permalink: true
  sane_lists: {}
  pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


# # Add toggle for English and Vietnamese language
#   extra:
#   alternate:
#     - name: English
#       link: /en/
#       lang: en
#     - name: Vietnamese
#       link: /vi/
#       lang: vi
